- name: ftp
  config:
    root: /var/lib/dionaea/wwwroot
    response_messages:
      welcome_msg: 220 DiskStation FTP server ready.

- name: http
  config:
    root: "/var/lib/dionaea/wwwroot"
    ports:
      - 80
    ssl_ports:
      - 443
    max_request_size: 32768 # maximum size in kbytes of the request (32MB)
    global_headers:
      - ["Server", "nginx"]
    headers:
      - filename_pattern: ".*\\.php"
        headers:
          - ["Content-Type", "text/html; charset=utf-8"]
          - ["Content-Length", "{content_length}"]
          - ["Connection", "{connection}"]
          - ["X-Powered-By", "PHP/5.5.9-1ubuntu4.5"]

- name: mqtt

- name: mysql
  config:
    databases:
      information_schema:
        path: ":memory:"
      # example how to extend this
      # just provide a databasename and path to the database
      # the database can be altered by attackers, so ... better use a copy
#      psn:
#        path: "/path/to/cc_info.sqlite"

- name: sip
  config:
    udp_ports:
      - 5060
    tcp_ports:
      - 5060
    tls_ports:
      - 5061
    users: "/tmp/sipaccounts.sqlite"
    rtp:
      enable: true
      # how to dump the rtp stream
      # bistream = dump as bistream
      modes:
        - bistream
        - pcap
      pcap:
        path: "var/dionaea/rtp/{personality}/%Y-%m-%d/"
        filename: "%H:%M:%S_{remote_host}_{remote_port}_in.pcap"
    personalities:
      default:
        domain: "localhost"
        name: "softphone"
        personality: "generic"
#      next-server:
#        domain: "my-domain"
#        name: "my server"
#        personality: "generic"
#        serve: ["10.0.0.1"]
#        default_sdp: "default"
#        handle: ["REGISTER", "INVITE", "BYE", "CANCEL", "ACK"]

    actions:
      bank-redirect:
        do: "redirect"
        params:
      play-hello:
        do: "play"
        params:
          file: "var/dionaea/.../file.ext"

- name: tftp
  config:
    root: /var/lib/dionaea/wwwroot

- name: upnp
  config:
    root: /var/lib/dionaea/wwwroot
    # maximum size in kbytes of the request (32MB)
    max_request_size: 32768
    personality:
      # default
      cache:    "CACHE-CONTROL: max-age=120\r\n"
      st:       "ST: upnp:rootdevice\r\n"
      usn:      "USN: uuid:Upnp-IPMI-1_0-1234567890001::upnp:rootdevice\r\n"
      server:   "SERVER: Linux/2.6.17.WB_WPCM450.1.3 UPnP/1.0, Intel SDK for UPnP devices/1.3.1\r\n"
      location: "LOCATION: http://192.168.0.1:49152/IPMIdevicedesc.xml\r\n"
      opt:      "OPT: http://schemas.upnp.org/upnp/1/0/\r\n"
#      # Samsung TV
#      cache:     "CACHE-CONTROL: max-age=900\r\n"
#      st:        "ST: uuid:c1fd12b2-d954-4dba-9e92-a697e1558fb4\r\n"
#      usn:       "USN: uuid:c1fd12b2-d954-4dba-9e92-a697e1558fb4\r\n"
#      server:    "SERVER: SHP, UPnP/1.0, Samsung UPnP SDK/1.0\r\n"
#      location:  "LOCATION: http://192.168.0.10:7677/MainTVServer2\r\n"
#      opt:       "OPT: http://schemas.upnp.org/upnp/1/0/\r\n"
#
#      # XBOX 360
#      cache:     "CACHE-CONTROL: max-age=1800\r\n"
#      st:        "ST: urn:microsoft.com:service:X_MS_MediaReceiverRegistrar:1\r\n"
#      usn:       "USN: uuid:531c567a-8c46-4201-bcd4-09afa554d859::urn:microsoft.com:service:X_MS_MediaReceiverRegistrar:1\r\n"
#      server:    "SERVER: Microsoft-Windows/6.3 UPnP/1.0 UPnP-Device-Host/1.0\r\n"
#      location:  "LOCATION: http://192.168.0.10:1055/upnphost/udhisapi.dll?content=uuid:531c567a-8c46-4201-bcd4-09afa554d859\r\n"
#      opt:       "OPT: http://schemas.upnp.org/upnp/1/0/\r\n"